apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smarttrip-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: smarttrip.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api 
            port:
              number: 8000